### ISSUE TITLE
node-red-contrib-scx-ibmiotapp must not require mqttConnectionPool

### ISSUE THREAD

**Issue by knolleary** [ibm-messaging/iot-nodered#12]
The node [requires the file `mqttConnectionPool`](https://github.com/ibm-messaging/iot-nodered/blob/master/node-red-contrib-scx-ibmiotapp/application/97-iotnewapp-cf.js#L20) from the core of node-red, but doesn't use it.

This file, `mqttConnectionPool` has been deprecated and will be removed in a future version of node-red. The require statement needs to be removed from this node asap.

**Comment by amitmangalvedkar** [comment]
I have modified the code and the `mqttConnectionPool` has been removed.
