### ISSUE TITLE
Update HDFS contrib for new Bluemix service name

### ISSUE THREAD

**Issue by kocolosk** [ibm-messaging/iot-nodered#3]
The service name shows up [here](https://github.com/ibm-messaging/iot-nodered/blob/master/node-red-contrib-bluemix-hdfs/application/47-ibmhdfs-cf.js#L36) and possibly elsewhere. It needs an update to match the new name of the Bluemix service.

**Comment by O-Hahn** [comment]
It is not only the renaming of the service. The integration API has also changed - so it has to be reworked.

**Comment by kocolosk** [comment]
Ah OK. Is the new API documented somewhere?

**Comment by O-Hahn** [comment]
I have raised an ticket in bluemix - and they told me that there will be an update..

**Comment by amitmangalvedkar** [comment]
This has been resolved sometime back.
