### ISSUE TITLE
Enhancement: Modifications in the device node

### ISSUE THREAD

**Issue by amitmangalvedkar** [ibm-messaging/iot-nodered#4]
This is an enhancement request
1. Change the default connection mode as Quickstart (currently its blank)
2. Hide the Authorization details in the Quickstart mode

**Comment by jeffdare** [comment]
This is implemented now with node-red-contrib-ibm-watson-iot.

**Comment by jeffdare** [comment]
Can now be installed via 
`npm install node-red-contrib-ibm-watson-iot`
